/**
 * @jest-environment node
 *
 * jsdom's FormData.append() stringifies any value that isn't an actual
 * instanceof its own Blob/File class (a plain object cast `as File` becomes
 * the literal string "[object Object]" on the far side of .get()) — and
 * jsdom's own File doesn't implement .arrayBuffer() either. Node's built-in
 * File/FormData (undici) do both correctly, and are what a real Next.js
 * server action receives, so this suite runs in the node environment and
 * uses real File instances instead of a duck-typed mock.
 */
jest.mock("@/auth", () => ({ auth: jest.fn() }))
jest.mock("@/lib/prisma", () => ({ prisma: { brandingAsset: { upsert: jest.fn(), delete: jest.fn() } } }))
jest.mock("@/lib/audit", () => ({ logAudit: jest.fn() }))
jest.mock("next/cache", () => ({ revalidatePath: jest.fn(), revalidateTag: jest.fn() }))

import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { uploadBranding, resetBranding } from "@/lib/actions/branding"
const mockAuth = auth as unknown as jest.Mock

// A fully valid 2×2 PNG (generated by sharp) — a corrupt fixture that only
// parses at the header level would pass sharp.metadata() but fail the real
// .png().toBuffer() transcode the action now performs.
const PNG_2x2 = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEUlEQVQImWPgEpH7D8IMMAYAJowE7bwlVOYAAAAASUVORK5CYII=", "base64")
const fileOf = (buf: Buffer, type = "image/png") => new File([new Uint8Array(buf)], "upload", { type })
const fd = (file: File) => { const f = new FormData(); f.append("file", file); return f }

beforeEach(() => jest.clearAllMocks())

test("rejects non-admin", async () => {
  mockAuth.mockResolvedValue({ user: { id: "1", role: "VIEWER" } })
  const r = await uploadBranding("logo", fd(fileOf(PNG_2x2)))
  expect(r).toEqual({ error: expect.any(String) })
  expect(prisma.brandingAsset.upsert).not.toHaveBeenCalled()
})

test("rejects unknown slot", async () => {
  mockAuth.mockResolvedValue({ user: { id: "1", role: "ADMIN" } })
  const r = await uploadBranding("bogus", fd(fileOf(PNG_2x2)))
  expect(r).toEqual({ error: expect.any(String) })
})

test("rejects disallowed mime", async () => {
  mockAuth.mockResolvedValue({ user: { id: "1", role: "ADMIN" } })
  const r = await uploadBranding("logo", fd(fileOf(Buffer.from("x"), "application/pdf")))
  expect(r).toEqual({ error: expect.any(String) })
})

test("rejects svg upload (stored-XSS vector)", async () => {
  mockAuth.mockResolvedValue({ user: { id: "1", role: "ADMIN" } })
  const svg = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>')
  const r = await uploadBranding("logo", fd(fileOf(svg, "image/svg+xml")))
  expect(r).toEqual({ error: expect.any(String) })
  expect(prisma.brandingAsset.upsert).not.toHaveBeenCalled()
})

test("admin upserts a valid png with dimensions", async () => {
  mockAuth.mockResolvedValue({ user: { id: "1", role: "ADMIN" } })
  const r = await uploadBranding("logo", fd(fileOf(PNG_2x2)))
  expect(r).toEqual({ success: expect.any(String) })
  expect(prisma.brandingAsset.upsert).toHaveBeenCalledWith(expect.objectContaining({
    where: { slot: "LOGO" },
    create: expect.objectContaining({ slot: "LOGO", mimeType: "image/png", width: 2, height: 2 }),
  }))
})

test("reset deletes the row (admin)", async () => {
  mockAuth.mockResolvedValue({ user: { id: "1", role: "ADMIN" } })
  ;(prisma.brandingAsset.delete as jest.Mock).mockResolvedValue({})
  const r = await resetBranding("crest")
  expect(r).toEqual({ success: expect.any(String) })
  expect(prisma.brandingAsset.delete).toHaveBeenCalledWith({ where: { slot: "CREST" } })
})
